CREATE TABLE IF NOT EXISTS public.voti_foto (
    file_name TEXT PRIMARY KEY,
    conteggio_voti INT DEFAULT 0
);

-- Permessi per far votare tutti
ALTER TABLE public.voti_foto ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Tutti possono vedere e votare" ON public.voti_foto FOR ALL USING (true) WITH CHECK (true);


CREATE TABLE IF NOT EXISTS public.commenti_foto (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_name TEXT REFERENCES public.voti_foto(file_name) ON DELETE CASCADE,
    testo TEXT,
    creato_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Permessi per i commenti
ALTER TABLE public.commenti_foto ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Commenti liberi" ON public.commenti_foto FOR ALL TO anon USING (true) WITH CHECK (true);

-- Aggiungiamo la colonna autore alla tabella voti (per chi carica la foto)
ALTER TABLE public.voti_foto ADD COLUMN IF NOT EXISTS autore TEXT DEFAULT 'Anonimo';

-- Aggiungiamo la colonna autore alla tabella commenti
ALTER TABLE public.commenti_foto ADD COLUMN IF NOT EXISTS autore TEXT DEFAULT 'Anonimo';

-- Tabella per tracciare i singoli voti
CREATE TABLE IF NOT EXISTS public.voti_per_utente (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_name TEXT REFERENCES public.voti_foto(file_name) ON DELETE CASCADE,
    nome_utente TEXT,
    UNIQUE(file_name, nome_utente) -- Impedisce doppioni a livello di database
);

-- Permessi
ALTER TABLE public.voti_per_utente ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Voti per utente accessibili" ON public.voti_per_utente FOR ALL TO anon USING (true) WITH CHECK (true);
